const ABI = [
  { inputs: [], stateMutability: 'nonpayable', type: 'constructor' },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint256', name: 'drawId', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: 'prize', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: 'drawTime', type: 'uint256' },
    ],
    name: 'DrawCreated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint256', name: 'drawId', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: 'winningTicket', type: 'uint256' },
      { indexed: false, internalType: 'address', name: 'winner', type: 'address' },
    ],
    name: 'DrawResult',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, internalType: 'uint256', name: 'drawId', type: 'uint256' }],
    name: 'NewLotteryStarted',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint256', name: 'drawId', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: 'winningTicket', type: 'uint256' },
    ],
    name: 'NoWinner',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint256', name: 'drawId', type: 'uint256' },
      { indexed: false, internalType: 'address', name: 'participant', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'ticketNumber', type: 'uint256' },
    ],
    name: 'ParticipantRegistered',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint256', name: 'drawId', type: 'uint256' },
      { indexed: false, internalType: 'address', name: 'winner', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'amount', type: 'uint256' },
    ],
    name: 'PrizeWithdrawn',
    type: 'event',
  },
  { inputs: [], name: 'buyTicket', outputs: [], stateMutability: 'payable', type: 'function' },
  {
    inputs: [],
    name: 'getCompletedDrawIds',
    outputs: [{ internalType: 'uint256[]', name: '', type: 'uint256[]' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getCurrentPrize',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_drawId', type: 'uint256' }],
    name: 'getDrawResult',
    outputs: [
      {
        components: [
          { internalType: 'uint256', name: 'drawId', type: 'uint256' },
          { internalType: 'uint256', name: 'winningTicket', type: 'uint256' },
          { internalType: 'address', name: 'winnerAddress', type: 'address' },
          { internalType: 'bool', name: 'hasWinner', type: 'bool' },
        ],
        internalType: 'struct DLottery.DrawPerformResult',
        name: '',
        type: 'tuple',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getLatestDrawResult',
    outputs: [
      {
        components: [
          { internalType: 'uint256', name: 'drawId', type: 'uint256' },
          { internalType: 'uint256', name: 'winningTicket', type: 'uint256' },
          { internalType: 'address', name: 'winnerAddress', type: 'address' },
          { internalType: 'bool', name: 'hasWinner', type: 'bool' },
        ],
        internalType: 'struct DLottery.DrawPerformResult',
        name: '',
        type: 'tuple',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getLotteryState',
    outputs: [{ internalType: 'string', name: '', type: 'string' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getParticipantCount',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getParticipants',
    outputs: [{ internalType: 'address[]', name: '', type: 'address[]' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getRandomTicket',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getTicketPrice',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'user', type: 'address' }],
    name: 'getUserTicket',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getWinner',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'isDrawCompleted',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'user', type: 'address' }],
    name: 'isOwner',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'isPrizeWithdrawn',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'user', type: 'address' }],
    name: 'isRegistered',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  { inputs: [], name: 'pause', outputs: [], stateMutability: 'nonpayable', type: 'function' },
  {
    inputs: [],
    name: 'performDraw',
    outputs: [
      {
        components: [
          { internalType: 'uint256', name: 'drawId', type: 'uint256' },
          { internalType: 'uint256', name: 'winningTicket', type: 'uint256' },
          { internalType: 'address', name: 'winnerAddress', type: 'address' },
          { internalType: 'bool', name: 'hasWinner', type: 'bool' },
        ],
        internalType: 'struct DLottery.DrawPerformResult',
        name: '',
        type: 'tuple',
      },
    ],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_ticketPrice', type: 'uint256' }],
    name: 'setTicketPrice',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'timestamp', type: 'uint256' }],
    name: 'startNewDraw',
    outputs: [],
    stateMutability: 'payable',
    type: 'function',
  },
  { inputs: [], name: 'unpause', outputs: [], stateMutability: 'nonpayable', type: 'function' },
  { inputs: [], name: 'withdrawPrize', outputs: [], stateMutability: 'nonpayable', type: 'function' },
];
const ADDRESS_CONTRACT = '0xD923882b4E5C5d6CfA061aDE4B5313d92d0aB502';

export { ABI, ADDRESS_CONTRACT };
